[package]
name = "simple_chat_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = "0.26.2"
futures = "0.3"
futures-util = "0.3.31"
http = "1.2.0"
url = "2.5"
ammonia = "4.0.0"
urlencoding = "2.1.3"